<?xml version="1.0" encoding="utf-8"?><Database Name="sasquatch" Class="CAIRSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sasquatch.cloudapp.net;Initial Catalog=sasquatch;Persist Security Info=True;User ID=team" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="sasquatchConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Reference" Member="References">
    <Type Name="Reference">
      <Column Name="ReferenceID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionResponseID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReferenceType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceString" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Association Name="QuestionResponse_Reference" Member="QuestionResponse" ThisKey="QuestionResponseID,RequestID" OtherKey="QuestionResponseID,RequestID" Type="QuestionResponse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Keyword" Member="Keywords">
    <Type Name="Keyword">
      <Column Name="KeywordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Keyword" Member="KeywordValue" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Keyword_KeywordQuestion" Member="KeywordQuestions" ThisKey="KeywordID" OtherKey="KeywordID" Type="KeywordQuestion" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionType" Member="QuestionTypes">
    <Type Name="QuestionType">
      <Column Name="QuestionTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="QuestionType_QuestionResponse" Member="QuestionResponses" ThisKey="QuestionTypeID" OtherKey="QuestionTypeID" Type="QuestionResponse" />
    </Type>
  </Table>
  <Table Name="dbo.Region" Member="Regions">
    <Type Name="Region">
      <Column Name="RegionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Region_Request" Member="Requests" ThisKey="RegionID" OtherKey="RegionID" Type="Request" />
    </Type>
  </Table>
  <Table Name="dbo.RequestorType" Member="RequestorTypes">
    <Type Name="RequestorType">
      <Column Name="RequestorTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="RequestorType_Request" Member="Requests" ThisKey="RequestorTypeID" OtherKey="RequestorTypeID" Type="Request" />
    </Type>
  </Table>
  <Table Name="dbo.TumourGroup" Member="TumourGroups">
    <Type Name="TumourGroup">
      <Column Name="TumourGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TumourGroup_QuestionResponse" Member="QuestionResponses" ThisKey="TumourGroupID" OtherKey="TumourGroupID" Type="QuestionResponse" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroup" Member="UserGroups">
    <Type Name="UserGroup">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UserGroup_UserGroups" Member="UserGroups" ThisKey="GroupID" OtherKey="GroupID" Type="UserGroups" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionResponse" Member="QuestionResponses">
    <Type Name="QuestionResponse">
      <Column Name="QuestionResponseID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="Response" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TimeSpent" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SpecialNotes" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="QuestionTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TumourGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Severity" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Consequence" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="QuestionResponse_Reference" Member="References" ThisKey="QuestionResponseID,RequestID" OtherKey="QuestionResponseID,RequestID" Type="Reference" />
      <Association Name="QuestionResponse_KeywordQuestion" Member="KeywordQuestions" ThisKey="QuestionResponseID,RequestID" OtherKey="QuestionResponseID,RequestID" Type="KeywordQuestion" />
      <Association Name="QuestionType_QuestionResponse" Member="QuestionType" ThisKey="QuestionTypeID" OtherKey="QuestionTypeID" Type="QuestionType" IsForeignKey="true" />
      <Association Name="TumourGroup_QuestionResponse" Member="TumourGroup" ThisKey="TumourGroupID" OtherKey="TumourGroupID" Type="TumourGroup" IsForeignKey="true" />
      <Association Name="Request_QuestionResponse" Member="Request" ThisKey="RequestID" OtherKey="RequestID" Type="Request" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Request" Member="Requests">
    <Type Name="Request">
      <Column Name="RequestID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentRequestID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="RequestorFName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="RequestorLName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="RequestorPhone" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="RequestorPhoneExt" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="RequestorEmail" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="PatientFName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="PatientLName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="PatientGender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="PatientAge" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="PatientAgencyID" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="RequestStatus" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="TimeOpened" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TimeClosed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestorTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Request_QuestionResponse" Member="QuestionResponses" ThisKey="RequestID" OtherKey="RequestID" Type="QuestionResponse" />
      <Association Name="Request_Request" Member="Requests" ThisKey="RequestID" OtherKey="ParentRequestID" Type="Request" />
      <Association Name="Request_RequestLock" Member="RequestLocks" ThisKey="RequestID" OtherKey="RequestID" Type="RequestLock" />
      <Association Name="Request_AuditLog" Member="AuditLogs" ThisKey="RequestID" OtherKey="RequestID" Type="AuditLog" />
      <Association Name="Region_Request" Member="Region" ThisKey="RegionID" OtherKey="RegionID" Type="Region" IsForeignKey="true" />
      <Association Name="Request_Request" Member="Request1" ThisKey="ParentRequestID" OtherKey="RequestID" Type="Request" IsForeignKey="true" />
      <Association Name="RequestorType_Request" Member="RequestorType" ThisKey="RequestorTypeID" OtherKey="RequestorTypeID" Type="RequestorType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RequestLock" Member="RequestLocks">
    <Type Name="RequestLock">
      <Column Name="RequestID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Request_RequestLock" Member="Request" ThisKey="RequestID" OtherKey="RequestID" Type="Request" IsForeignKey="true" />
      <Association Name="UserProfile_RequestLock" Member="UserProfile" ThisKey="UserID" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(56) NOT NULL" CanBeNull="false" />
      <Column Name="UserFullName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserEmail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UserProfile_RequestLock" Member="RequestLocks" ThisKey="UserId" OtherKey="UserID" Type="RequestLock" />
      <Association Name="UserProfile_UserGroups" Member="UserGroups" ThisKey="UserId" OtherKey="UserID" Type="UserGroups" />
      <Association Name="UserProfile_AuditLog" Member="AuditLogs" ThisKey="UserId" OtherKey="UserID" Type="AuditLog" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroups" Member="UserGroups1">
    <Type Name="UserGroups">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UserGroup_UserGroups" Member="UserGroup" ThisKey="GroupID" OtherKey="GroupID" Type="UserGroup" IsForeignKey="true" />
      <Association Name="UserProfile_UserGroups" Member="UserProfile" ThisKey="UserID" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KeywordQuestion" Member="KeywordQuestions">
    <Type Name="KeywordQuestion">
      <Column Name="KeywordID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QuestionResponseID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Keyword_KeywordQuestion" Member="Keyword" ThisKey="KeywordID" OtherKey="KeywordID" Type="Keyword" IsForeignKey="true" />
      <Association Name="QuestionResponse_KeywordQuestion" Member="QuestionResponse" ThisKey="QuestionResponseID,RequestID" OtherKey="QuestionResponseID,RequestID" Type="QuestionResponse" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AuditLog" Member="AuditLogs">
    <Type Name="AuditLog">
      <Column Name="RequestID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AuditType" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AuditDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UserProfile_AuditLog" Member="UserProfile" ThisKey="UserID" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
      <Association Name="Request_AuditLog" Member="Request" ThisKey="RequestID" OtherKey="RequestID" Type="Request" IsForeignKey="true" />
    </Type>
  </Table>
</Database>